### ISSUE TITLE
Refresh Frequency

### ISSUE THREAD

**Issue by dopplebockk** [kknopper/ubersicht-calendar#1]
Hey there kknopper,

Firstly, thank you for being my proper introduction to ubersicht. I had been a geektool user for years, but never went further than a basic desktop clock. Your calendar opened me up to scripting again.

**Line 3:**
`export const refreshFrequency = 3600000; //update every hour`

I just glanced at mine and it had not refreshed in a few days. What is the 3,600,000 figure measured in units? I see your note about an update every hour, and I was curious if you ever experienced this issue. Only things that I've modified to your original code were related to the css elements.

**Comment by kknopper** [comment]
Hey  @dopplebockk,

Glad my widget inspired you! :D I used to use geektool back in the day as well, until I found übersicht.

The refreshFrequency variable is in milliseconds.
[https://github.com/felixhageloh/uebersicht#refreshfrequency](https://github.com/felixhageloh/uebersicht#refreshfrequency)

I've been using übersicht on my laptop, so every time I open my computer my widgets get refreshed.

Reading through the docs again though, it looks like I wrote this widget incorrectly. The refreshFrequency works by rerunning the command function. So I will have to move all the logic into that function.

I've started working on a fix, but it's still a work in progress. This is the first widget that I've written myself, so I'm still getting the hang of the new übersicht syntax.

**Comment by dopplebockk** [comment]
I'd be happy to help debug if you would supply your existing change(s) and/or the link to the documentation for my own reference!

**Comment by kknopper** [comment]
@dopplebockk this should be working for you now, lemme know if there's any issues.

**Comment by dopplebockk** [comment]
Cleaned it right up, thank you. [desktop](https://i.imgur.com/KAVhLjw.jpg)
